process.on('uncaughtException', (err) => {
  console.error('üî• Uncaught Exception:', err)
  process.exit(1)
})

import 'dotenv/config'
import app from './app.js'
import { connectToDB, disconnectFromDB } from './utils/index.js'
import config from './config/index.js'
import { type Server } from 'http'

const {
  port,
  databaseURI,
  databaseName,
  databaseConnectionOptions,
  environments
} = config

let server: Server | undefined = undefined

// üí• Global unhandled rejection handler
process.on('unhandledRejection', (err) => {
  console.error('üí• Unhandled Rejection:', err)

  if (!server) {
    console.log('No server to close. Exiting...')
    process.exit(1)
  }

  server.close(() => {
    console.log('üßº Closing server and cleaning up...')
    ;(async () => {
      try {
        await disconnectFromDB()
        console.log('‚úÖ DB disconnected')
      } catch (disconnectErr) {
        console.error('‚ùå Failed to disconnect DB:', disconnectErr)
      } finally {
        process.exit(1)
      }
    })()
  })
})

const main = async (): Promise<void> => {
  try {
    await connectToDB(databaseURI, databaseName, databaseConnectionOptions)

    server = app.listen(port, () => {
      console.log(`now you are in ${environments} listening to port ${port}`)
    })
  } catch (err) {
    console.error('‚ùå Error during startup:', err)
  }
}

main().then(() => {
  console.log('‚úÖ App is running')
})
